########################################################################################
########################################################################################
### Influenza Ferret Blood Chemistry & Clinical Symptoms Data Analysis
### HemaVet/VetScan data generated by 
###       Joanna Pulit-Penaloza & Afton Barkes (Vet Resident)
### primary analyses and plots
### 11 September 2025 - 30 July 2026
### Troy J. Kieran
########################################################################################
########################################################################################
### Load packages
library(tidyverse)
library(tidylog)
library(patchwork)
library(colorspace) ## for color shading
library(lme4)
library(emmeans)

########################################################################################
### Import Data

## blood chemistry & complete blood counts data
blood <- read.csv("R_inputs/allBlood_data.csv", header = TRUE, check.names = FALSE)
## clinical data
clinical <- read.csv("R_inputs/Clinical_data.csv", header = TRUE, check.names = FALSE)
## manual adjust missing Day titers, 10 for LOD, 2 for euth
NW_titers <- read.csv("R_inputs/NW_titers_modified.csv", header = TRUE)

########################################################################################

## ALP & AMY values at '< 5' set to 2.5
## CRE value at '< 0.2' set to 0.1
## Optional: Day set to factor and re-leveled
## Fix dates

blood <- blood %>%
  ## set limit of detection values to mid-point of 0 and LOD
  mutate(CRE = case_when(str_detect(CRE, "<0.2\\*") ~ 0.1, TRUE ~ as.numeric(CRE)),
         ALP = case_when(str_detect(ALP, "<5\\*") ~ 2.5, TRUE ~ as.numeric(ALP)),
         Date = as.Date(Date, origin = "1899-12-30")) 

clinical <- clinical %>%
  mutate(ID  = str_replace(ID, " -survived", ""),
         Date = as.Date(Date, origin = "1899-12-30"),
         Virus = fct_relevel(Virus, "H1N1", "H3N2", "H5_MI90", 
                             "H1N1_TX37", "H3N2_TX37", "H5_TX37")) %>%
  mutate(euth_today = if_else(euth == "yes", 1L, 0L, missing = 0L)) %>%
  group_by(Virus, ID) %>%
  mutate(euth_day_num = if (any(euth_today == 1, na.rm = TRUE))
    min(Day[euth_today == 1], na.rm = TRUE) else NA_integer_,
    euth_final   = as.integer(any(euth_today == 1, na.rm = TRUE))) %>%
  ungroup()

## combine data
data <- clinical %>%
  full_join(blood, by = c("Virus", "ID", "Day", "Date",
                          "Treatment", "Group1", "Group2"),
            relationship = "many-to-many")

########################################################################################

### Renamed labels for facets & Set colors

## Virus - need to determine labels
virus_labs  <- c(H1N1 = "A(H1N1)pdm09 NE/14", H3N2 = "A(H3N2) MA/18", 
                 H5_MI90 = "A(H5N1) MI/90", H5_TX37 = "A(H5N1) TX/37",
                 H1N1_TX37 = "A(H1N1)pdm09 -> TX/37", H3N2_TX37 = "A(H3N2) -> TX/37")

## Fix Virus colors
## https://imagecolorpicker.com/
virus_colors <- c(
  "H1N1"      = "#fd8603",
  "H1N1_TX37" = "#005be2",
  "H3N2"      = "#61cbf4",
  "H3N2_TX37" = "#fce014",
  "H5_MI90"   = "#009200",
  "H5_TX37"   = "#b800b8")

## set virus order
NW_titers$Virus <- factor(NW_titers$Virus, levels = names(virus_labs))

########################################################################################

### Summary Stats

## function to selectively round based on value
smart_round <- function(x) {
  ifelse(abs(x) >= 1,
         # numbers ≥ 1 to 1 decimal place
         round(x, 1),   
         ## numbers < 1 to 2 decimal places
         round(x, 2)) }

blood_summary <- blood %>%
  select(Virus, Day, where(is.numeric)) %>%  ## keep Virus, Day + numeric columns
  pivot_longer(-c(Virus, Day), names_to = "variable", values_to = "value") %>%
  group_by(Virus, Day, variable) %>%
  reframe(
    N = sum(!is.na(value)),
    min = min(value, na.rm = TRUE),
    max = max(value, na.rm = TRUE),
    med = median(value, na.rm = TRUE),
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE),
    se = sd / sqrt(N),
    CI.l.mean = mean - qt(0.975, df = N - 1) * sd / sqrt(N),
    CI.u.mean = mean + qt(0.975, df = N - 1) * sd / sqrt(N)) %>%
  ## round all numbers except N to 1 digit
  mutate(across(where(is.numeric) & !c(N), smart_round)) %>%
  filter(N > 0) %>%
  ## paste together variables with parentheses for consolidated table
  mutate(mean_range = paste0(mean, " (", min, "-", max, ")")) #%>%
  ## consistent decimals
  #mutate(summary = sprintf("%.2f (%.2f-%.2f)", mean_val, min_val, max_val))

#write.csv(blood_summary, file = 'blood_summary_stats_rounded.csv')

set.seed(123)
baseline_summary <- blood %>%
  filter(Day %in% c(-4, 0)) %>%
  select(Day, where(is.numeric)) %>%  ## keep Day + numeric columns
  pivot_longer(WBC:GLOB, names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  reframe(
    N = sum(!is.na(value)),
    min = min(value, na.rm = TRUE),
    max = max(value, na.rm = TRUE),
    med = median(value, na.rm = TRUE),
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE),
    se = sd / sqrt(N),
    CI.l.mean = mean - qt(0.975, df = N - 1) * sd / sqrt(N),
    CI.u.mean = mean + qt(0.975, df = N - 1) * sd / sqrt(N),
    ## raw percentiles
    RI  = list(quantile(value, probs = c(0.025, 0.975), na.rm = TRUE)),
    RI2 = list(quantile(value, probs = c(0.05, 0.95), na.rm = TRUE)),
    ## bootstrap percentiles
    boot_RI = list({
      n_boot <- 5000
      boot_samples <- replicate(n_boot, sample(value, replace = TRUE))
      boot_percentiles <- apply(boot_samples, 2, function(x) 
        quantile(x, probs = c(0.025, 0.975), na.rm = TRUE))
      rowMeans(boot_percentiles)}),
    boot_RI2 = list({
      n_boot <- 5000
      boot_samples <- replicate(n_boot, sample(value, replace = TRUE))
      boot_percentiles <- apply(boot_samples, 2, function(x) 
        quantile(x, probs = c(0.05, 0.95), na.rm = TRUE))
      rowMeans(boot_percentiles)}),
    
    ## quantiles
    Q1 = quantile(value, 0.25, na.rm = TRUE),
    Q3 = quantile(value, 0.75, na.rm = TRUE),
    IQR = Q3 - Q1,
    ## Tukey's fences - outlier detection
    lower_fence = Q1 - 1.5 * IQR,   ## 1.5 mild outliers, 3 for extreme outliers
    upper_fence = Q3 + 1.5 * IQR,
    #outlier_iqr = value < lower_fence | value > upper_fence,
    ## MAD (median absolute deviation) - outlier detection
    mad_val = mad(value, constant = 1, na.rm = TRUE), ## 1 for raw MAD, 1.4826 for scaled = SD like
    #outlier_mad = abs(value - med) > 3 * mad_val, ## 3 strict, 2.5 for moderate
    
    ### measures of data variability:
    ## Gini coefficient - measure of variability, 0-1
    gini = DescTools::Gini(value, na.rm = TRUE),
    ## Coefficient of Variation (CV)
    cv = (sd / mean) * 100,
    ## Robust CV based on IQR (RCV𝑄)
    rcvq = (0.75 * (IQR/med)) * 100,
    ## Robust CV based on MAD (RCV𝑀)
    rcvm = (1.4826 * (mad_val/med)) * 100) %>%
  unnest_wider(RI, names_sep = "_") %>%
  unnest_wider(RI2, names_sep = "_") %>%
  unnest_wider(boot_RI, names_sep = "_boot") %>%
  unnest_wider(boot_RI2, names_sep = "_boot") %>%
  ungroup()

baseline_summary <- baseline_summary %>%
  ## round all numbers except N to 1 digit
  mutate(across(where(is.numeric) & !c(N), smart_round)) %>%
  ## paste together variables with parentheses for consolidated table
  mutate(mean_range = paste0(mean, " (", min, "-", max, ")"),
         lower_fence = abs(lower_fence),
         #lower_fence = ifelse(lower_fence < 0, 0, lower_fence),
         Tukey_range = paste0(mean, " (", lower_fence, "-", upper_fence, ")"))

# write.csv(baseline_summary, file = 'baseline_summary_stats_rounded.csv')

########################################################################################

### long format data

## which variables are numeric (exclude non-numeric)
lab_cols <- setdiff(names(blood), c("Virus", "Treatment", "Group1", "Group2",
                                    "ID", "Day", "Date", "Notes"))

blood_long <- blood %>%
  pivot_longer(all_of(lab_cols), names_to = "variable", values_to = "value") %>%
  ## create groups based on variable value size/range
  mutate(Group = case_when(
    variable %in% c('PLT', 'ALT') ~ 'Group A',
    variable %in% c('NA', 'GLU') ~ 'Group B',
    variable %in% c('NEU_p', 'LYM_p') ~ 'Group C',
    variable %in% c('NE_p', 'LY_p', 'HCT', 'MCV', 'MCHC') ~ 'Group D',
    variable %in% c('BUN', 'AMY', 'ALP') ~ 'Group E',
    variable %in% c('HGB', 'RDW', 'MCH') ~ 'Group F',
    variable %in% c('WBC', 'RBC', 'MPV', 'MON_p', 'MO_p', 
                    'LY', 'Hb', 'PHOS', 'CA') ~ 'Group G',
    variable %in% c('NEU', 'LYM', 'EOS_p', 'TP', 'ALB', 'K') ~ 'Group H',
    TRUE ~ 'Group I')) %>%
  mutate(Group = factor(Group, levels = c('Group A', 'Group B', 'Group C', 
                                          'Group D', 'Group E', 'Group F', 
                                          'Group G', 'Group H', 'Group I')))

clinical_sym_long <- clinical %>%
  select(-Anemia, -Hydration) %>%
  mutate(Fever = if_else(!is.na(Temp) & Temp > 40, 1L, 0L),
         NW_detect = if_else(NW > 0, 1L, 0L, missing = NA_integer_),
         RS_detect = if_else(RS > 0, 1L, 0L, missing = NA_integer_),
         BD_detect = if_else(BD > 0, 1L, 0L, missing = NA_integer_),
         wt_loss_7p5 = if_else(!is.na(wt_loss_cum_p) & wt_loss_cum_p >= 7.5, 1L, 0L),
         wt_loss_10 = if_else(!is.na(wt_loss_cum_p) & wt_loss_cum_p >= 10, 1L, 0L),
         wt_loss_15 = if_else(!is.na(wt_loss_cum_p) & wt_loss_cum_p >= 15, 1L, 0L),
         wt_loss_17p5 = if_else(!is.na(wt_loss_cum_p) & wt_loss_cum_p >= 17.5, 1L, 0L),
         wt_loss_20 = if_else(!is.na(wt_loss_cum_p) & wt_loss_cum_p >= 20, 1L, 0L),
         wt_loss_22p5 = if_else(!is.na(wt_loss_cum_p) & wt_loss_cum_p >= 22.5, 1L, 0L)) %>% 
  mutate(across(Nasal_Discharge:Yellow_Sera,
                ~ case_when(. == "Y" ~ 1L,
                            . == "N" ~ 0L, 
                            is.na(.) ~ NA_integer_, TRUE ~ NA_integer_ ))) %>%
  mutate(across(Mentation,
                ~ case_when(. == 'B' ~ 0,
                            . == 'Q' ~ 0,
                            . == 'D' ~ 0.75,
                            . == 'O' ~ 1.75,
                            . == 'S' ~ 2.25,
                            . == 'M' ~ 3,
                            is.na(.) ~ NA_integer_, TRUE ~ NA_integer_ ))) %>%
  pivot_longer(cols = c(Lethargy:Yellow_Sera, Fever:BD_detect, wt_loss_10),
               #cols = c(Lethargy:Diarrhea, Fever:wt_loss_22p5),
               names_to = "symptom",
               values_to = "symptom_value") %>%
  mutate(symptom_present = if_else(symptom_value > 0, 1L, 0L, missing = 0L))

########################################################################################

### Viral titer measurements - Figure 1

# subset data
clinical_sym_long %>%
  mutate(NW = ifelse(NW == 0, 10, NW)) %>%
  filter(Day %in% c(1, 2, 4, 6, 7, 8, 10)) %>%
  select(Virus, ID, Day, NW) %>%
  distinct() %>%
  write.csv(file = "NW_titers.csv")

## color shading ferrets to match 'virus_colors', with black bars below LOD/euth

## function to make n shades around a base color
make_shades <- function(base, n) {
  if (n <= 1) return(rep(base, n))
  ramp <- grDevices::colorRampPalette(
    c(lighten(base, 0.4), base, darken(base, 0.4)))
  ramp(n) }

## one color per ID, shaded by its Virus' base color
id_key <- NW_titers %>%
  distinct(Virus, ID) %>%
  arrange(Virus, ID) %>%
  group_split(Virus) %>%
  map_dfr(function(d) {
    base <- virus_colors[as.character(d$Virus[1])]
    d$shade <- make_shades(base, nrow(d))
    d }) %>%
  ## colors for each Virus-ID combo
  mutate(VID = interaction(Virus, ID, drop = TRUE))

## colors for each ferret ID
id_colors <- setNames(id_key$shade, id_key$ID)
## color for euth ferret bars below LOD
pal <- c(id_colors, "below" = "black")

## summarize to the means
ID_df <- NW_titers %>%
  group_by(Virus, ID, Day) %>%
  summarise(mean_log10 = mean(log10(NW), na.rm = TRUE), .groups = "drop") %>%
  mutate(fill_key = ifelse(mean_log10 < 1, "below", as.character(ID)))

## add asterisk to point out day 7 v 8 - 25 June 2026
asterisk_df <- data.frame(
  Virus = factor("H3N2_TX37", levels = names(virus_labs)),
  Day = factor(8, levels = levels(factor(ID_df$Day))),
  fill_key = "T7721",
  mean_log10 = 3,
  label = "*")

## colors for each ferret ID
ID_df %>%
  mutate(Virus = factor(Virus, levels = c("H1N1", "H3N2", "H5_MI90", 
                                          "H5_TX37", "H1N1_TX37", "H3N2_TX37"))) %>%
  ggplot(aes(x = factor(Day), y = mean_log10, fill = fill_key)) +
  geom_col(width = 0.7, position = position_dodge2(preserve = "single")) +
  geom_hline(yintercept = 1, linetype = "dashed", linewidth = 0.2) +
  geom_text(
    data = asterisk_df,
    aes(x = Day, y = mean_log10, label = label, group = fill_key),
    inherit.aes = FALSE,
    position = position_dodge2(width = 0.7, preserve = "single"),
    color = "red4", size = 4) +
  facet_wrap(vars(Virus), labeller = labeller(
    Virus = as_labeller(
      c(H1N1      = "bold(a)~\"A(H1N1)pdm09 NE/14\"",
        H3N2      = "bold(b)~\"A(H3N2) MA/18\"",
        H5_MI90   = "bold(c)~\"A(H5N1) MI/90\"",
        H5_TX37   = "bold(d)~\"A(H5N1) TX/37\"",
        H1N1_TX37 = "bold(e)~\"A(H1N1)\" %->% \"TX/37\"",
        H3N2_TX37 = "bold(f)~\"A(H3N2)\" %->% \"TX/37\""),
      label_parsed)), nrow = 3, ncol = 2, scales = "free_y") +
  scale_fill_manual(values = pal, name = "ID") +
  labs(x = "Day Post-inoculation", 
       y = expression('Nasal Wash Titers (' * log[10] * ' PFU/mL)')) +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"), 
        strip.text.x = element_text(size = 16),
        legend.text = element_text(size = 13),
        axis.title = element_text(size = 13),
        axis.text = element_text(size = 13), 
        legend.position = "none",  
        panel.grid = element_blank(),
        axis.line = element_line(color = "black")) -> plot_NW_titers_v2

# ragg::agg_tiff(filename = "plot_NW_titers_DayvVirus_ID_august_9.tiff",
#                width = 12, height = 10, units = 'cm', res = 600,
#                scaling = 0.7, compression = "lzw")
# plot(plot_NW_titers_v2)
# invisible(dev.off())

########################################################################################

### Summary Plots of Clinical Data

## missingness overview (quick check)
naniar::vis_miss(clinical %>% select(Virus, ID, Day, Date, Weight, Temp, NW, RS, BD))

### Figure 2

## summaries with uncertainty
clinical %>% 
  filter(Day != -4) %>%
  filter(Day < 15) %>%
  mutate(Virus = factor(Virus, levels = c("H1N1", "H3N2", "H5_MI90", 
                                          "H5_TX37", "H1N1_TX37", "H3N2_TX37"))) %>%
  group_by(Virus, Day) %>% 
  reframe(mean_temp = mean(temp_change, na.rm = TRUE),
          sd_temp = sd(temp_change, na.rm = TRUE),
          n = sum(!is.na(temp_change)),
          se_temp = sd_temp / sqrt(pmax(n, 1))) %>%
  ggplot(aes(Day, mean_temp, color = Virus, fill = Virus)) +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  geom_line(linewidth = 1.2) +
  scale_color_manual(values = virus_colors, labels = virus_labs) +
  scale_fill_manual(values = virus_colors, labels = virus_labs) +
  scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12, 14)) +
  labs(y = expression("Temperature Change " *~(degree*C)),
       x = "Day Post-inoculation") +
  guides(color = guide_legend(ncol = 4, byrow = TRUE)) +
  theme_minimal() +
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        legend.text = element_text(size = 13),
        strip.text.x = element_text(size = 13),
        axis.title = element_text(size = 13),
        axis.text = element_text(size = 13)) -> plot_mean_temp_change

clinical %>% 
  filter(Day != -4) %>%
  filter(Day < 15) %>%
  mutate(Virus = factor(Virus, levels = c("H1N1", "H3N2", "H5_MI90", 
                                          "H5_TX37", "H1N1_TX37", "H3N2_TX37"))) %>%
  group_by(Virus, Day) %>%
  reframe(mean_weight = mean(weight_change, na.rm = TRUE),
          sd_weight = sd(weight_change, na.rm = TRUE),
          n = sum(!is.na(weight_change)),
          se_weight = sd_weight / sqrt(pmax(n, 1))) %>%
  ggplot(aes(Day, mean_weight, color = Virus, fill = Virus)) +
  geom_hline(yintercept = 100, linetype = 'dashed') +
  geom_line(linewidth = 1.2) +
  scale_color_manual(values = virus_colors, labels = virus_labs) +
  scale_fill_manual(values = virus_colors, labels = virus_labs) +
  scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12, 14)) +
  labs(y = "Weight Change (%)",
       x = "Day Post-inoculation") +
  guides(color = guide_legend(ncol = 4, byrow = TRUE)) +
  theme_minimal() +
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        strip.text.x = element_text(size = 13),
        legend.text = element_text(size = 13),
        axis.title = element_text(size = 13),
        axis.text = element_text(size = 13)) -> plot_mean_weight_change

###

plot_weight_temp <- (plot_mean_temp_change | plot_mean_weight_change) + 
  plot_annotation(tag_levels = 'a') + 
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom",
    plot.tag = element_text(size = 25),
    plot.tag.position = c(-0.015, 1), 
    panel.grid = element_blank(), 
    axis.line = element_line(color = "black"))

# ragg::agg_tiff(filename = "plot_weight_temp_change_DayvVirus_august-9.tiff",
#                width = 15, height = 7.2, units = 'cm', res = 600,
#                scaling = 0.7, compression = "lzw")
# plot(plot_weight_temp)
# invisible(dev.off())

########################################################################################

### Clinical Symptoms - Figure 3

## summary symptom score
clinical_sym_score <- clinical_sym_long %>%
  group_by(Virus, ID, Date, Day) %>%
  reframe(symptom_score = sum(symptom_present, na.rm = TRUE),
          symptom_present = replace(symptom_present, is.na(symptom_value), NA))

## heatmap of symptom prevalence
clinical_sym_long %>%
  filter(Day >= 0,
         Day < 15,
         symptom != 'Mentation',
         symptom != 'Neuro',
         symptom != 'Yellow_Sera',
         symptom != 'BD_detect',
         symptom != 'RS_detect',
         symptom != 'NW_detect') %>%
  mutate(symptom = recode(symptom, "wt_loss_10" = "Weight_Loss >10%"),
         symptom = recode(symptom, "Fever" = "Fever >40C"),
         Virus = factor(Virus, levels = c("H1N1", "H3N2", "H5_MI90", 
                                          "H5_TX37", "H1N1_TX37", "H3N2_TX37"))) %>%
  group_by(Virus, Day, symptom) %>%
  #reframe(prop = mean(symptom_present, na.rm = TRUE)) %>%
  reframe(sum = sum(symptom_present, na.rm = TRUE)) %>%
  mutate(sum = factor(sum, levels = c(0, 1, 2, 3))) %>%
  ggplot(aes(x = factor(Day), y = symptom, fill = sum)) +
  geom_tile(color = "white", linewidth = 0.2) +
  scale_fill_viridis_d(option = "magma", end = 0.99, direction = -1,
                       limits = c("0", "1", "2", "3"),
                       breaks = c("0", "1", "2", "3"),
                       drop = FALSE) +
  # facet_wrap(~ Virus, labeller = labeller(Virus = as_labeller(virus_labs)),
  #            nrow = 3, ncol = 2) +
  facet_wrap(vars(Virus), labeller = labeller(
    Virus = as_labeller(
      c(H1N1      = "bold(a)~\"A(H1N1)pdm09 NE/14\"",
        H3N2      = "bold(b)~\"A(H3N2) MA/18\"",
        H5_MI90   = "bold(c)~\"A(H5N1) MI/90\"",
        H5_TX37   = "bold(d)~\"A(H5N1) TX/37\"",
        H1N1_TX37 = "bold(e)~\"A(H1N1)pdm09\" %->% \"TX/37\"",
        H3N2_TX37 = "bold(f)~\"A(H3N2)\" %->% \"TX/37\""),
      label_parsed)), nrow = 3, ncol = 2) +
  labs(x = "Day Post-inoculation", y = NULL, fill = "Number of Ferrets") +
  scale_y_discrete(labels = c(
    "Ab_Breathing" = "Abnormal Breathing",
    "BD_detect" = "Viremia",
    "Decrease_or_Lack_Grooming" = "Decreased Grooming",
    "Facial" = "Grimace",
    "Fever >40C" = expression("Fever >40"~degree*C),
    "Nasal_Discharge" = "Nasal Discharge",
    "Neuro" = "Neurological",
    "NW_detect" = "Nasal Wash Titers",
    "RS_detect" = "Rectal Swab Titers",
    "Weight_Loss >10%" = "Weight Loss >10%",
    "Yellow_Sera" = "Yellow Sera"),
    limits = c(
      "Ab_Breathing", "Decrease_or_Lack_Grooming",
      "Hunched", "Facial", 'Diarrhea', "Sneeze",
      "Nasal_Discharge", "Fever >40C", "Weight_Loss >10%",
      "Lethargy")) +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"),
        strip.text = element_text(face = "bold"),
        legend.position = 'bottom',
        legend.title = element_text(size = 13),
        legend.text = element_text(size = 13),
        strip.text.x = element_text(size = 16),
        axis.title = element_text(size = 13),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13)) +
  # guides(fill = guide_colorbar(
  #   barwidth  = unit(5, "cm"),  ## make longer, when at bottom
  #   barheight = unit(0.2, "cm"), ## make taller, when at bottom
  #   ticks = TRUE)) + 
  guides(fill = guide_legend(nrow = 1)) -> plot_symptom_prevalence

# ragg::agg_tiff(filename = "plot_symptom_prevalence_DayvVirus_august9.tiff",
#                width = 15, height = 15, units = 'cm', res = 600,
#                scaling = 0.7, compression = "lzw")
# plot(plot_symptom_prevalence)
# invisible(dev.off())

########################################################################################

## which variables are numeric (exclude non-numeric)
#lab_cols <- setdiff(names(blood), c("Virus", "ID", "Day", "Date", "Notes"))

## baseline data
baseline <- data %>%
  filter(Day %in% c(-4, 0)) %>%
  pivot_longer(all_of(lab_cols), names_to = "variable", values_to = "value") %>%
  group_by(ID, variable) %>%
  reframe(mean_baseline = mean(value, na.rm = TRUE))

## combine 
data_long <- data %>%
  pivot_longer(all_of(lab_cols), names_to = "variable", values_to = "value") %>%
  left_join(baseline, by = c("ID", "variable")) %>%
  mutate(delta    = value - mean_baseline,
         ratio    = value / mean_baseline,
         logratio = log(ratio)) ## for skewed chemistry

## check data for Inf & NaN values
sapply(data_long, function(x) any(is.infinite(x)))
sapply(data_long, function(x) any(is.nan(x)))
## found in 'ratio' columns

## set Inf & NaN values to NA
data_long[sapply(data_long, is.infinite)] <- NA
data_long[sapply(data_long, is.nan)] <- NA

########################################################################################

### Baseline Range

baseline_ranges <- blood %>%
  filter(Day %in% c(-4, 0)) %>%
  select(Day, where(is.numeric)) %>%
  pivot_longer(WBC:GLOB, names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  summarise(RI = list(quantile(value, probs = c(0.025, 0.975), na.rm = TRUE))) %>%
  tidyr::unnest_wider(RI, names_sep = "_")

###

## create a ribbon dataframe that spans the full Day range for each variable
ribbon_df <- data_long %>%
  filter(!str_detect(variable, "_p")) %>%
  filter(Day > 0) %>%
  distinct(variable, Day) %>%
  left_join(baseline_ranges) %>%
  rename(RI_low = `RI_2.5%`, RI_high = `RI_97.5%`)

########################################################################################

### Figure 4

data_long %>% 
  filter(!str_detect(variable, "_p")) %>%
  filter(variable %in% c('LYM', 'NEU')) %>%
  mutate(variable = fct_relevel(variable, "LYM", "NEU"),
         variable = droplevels(variable),
         Virus = factor(Virus, levels = c('H1N1', 'H3N2', 'H5_MI90', 
                                          'H5_TX37', 'H1N1_TX37', 'H3N2_TX37'))) %>%
  filter(Day > 0) %>%
  ## filter out data from euth ferrets not on collection day
  filter(!(Virus == 'H1N1_TX37' & ID == 'T7724' & Day == 11),
         !(Virus == 'H3N2_TX37' & ID == 'T7721' & Day == 7),
         !(Virus == 'H3N2_TX37' & ID == 'T7720' & Day == 8)) %>%
  ggplot(aes(x = Day, y = value, color = Virus, group = ID)) +
  geom_ribbon(data = ribbon_df %>%
                filter(variable %in% c('LYM', 'NEU')),
              aes(x = Day, ymin = RI_low, ymax = RI_high),
              inherit.aes = FALSE, fill = "gray80", alpha = 0.4) +
  ## mean line
  stat_summary(aes(group = Virus), fun = mean,
               geom = "line", linewidth = 1.1) +
  scale_color_manual(values = virus_colors, labels = virus_labs) +
  scale_fill_manual(values = virus_colors, labels = virus_labs) +
  scale_x_continuous(breaks = seq(min(data_long$Day), max(data_long$Day), by = 4)) +
  facet_wrap(vars(variable),
    labeller = labeller(
      variable = c(LYM = "bold(a)~Lymphocytes", NEU = "bold(b)~Neutrophils"),
      .default = label_parsed), nrow = 1, scales= "free_y") +
  labs(y = expression(10^3 ~ "/ " * mu * "L"), x = "Day Post-inoculation") +
  theme_minimal() +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        axis.line = element_line(color = "black"), 
        legend.text = element_text(size = 13),
        strip.text.x = element_text(size = 16),
        axis.title = element_text(size = 13),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13)) +
  guides(color = guide_legend(ncol = 4, byrow = TRUE)) -> plot_hema1_raw_mean

data_long %>% 
  filter(!str_detect(variable, "_p")) %>%
  filter(variable %in% c('MON', 'EOS', 'BAS')) %>%
  mutate(variable = factor(variable),
         variable = droplevels(variable),
         variable = factor(variable, levels = c("MON", "EOS", "BAS")),
         Virus = factor(Virus, levels = c('H1N1', 'H3N2', 'H5_MI90', 
                                          'H5_TX37', 'H1N1_TX37', 'H3N2_TX37'))) %>%
  filter(Day > 0) %>%
  ## filter out data from euth ferrets not on collection day
  filter(!(Virus == 'H1N1_TX37' & ID == 'T7724' & Day == 11),
         !(Virus == 'H3N2_TX37' & ID == 'T7721' & Day == 7),
         !(Virus == 'H3N2_TX37' & ID == 'T7720' & Day == 8)) %>% 
  ggplot(aes(x = Day, y = value, color = Virus, group = ID)) +
  geom_ribbon(data = ribbon_df %>%
                filter(variable %in% c('MON', 'EOS', 'BAS')),
              aes(x = Day, ymin = RI_low, ymax = RI_high),
              inherit.aes = FALSE, fill = "gray80", alpha = 0.4) +
  ## mean line
  stat_summary(aes(group = Virus), fun = mean,
               geom = "line", linewidth = 1.1) +
  scale_color_manual(values = virus_colors, labels = virus_labs) +
  scale_fill_manual(values = virus_colors, labels = virus_labs) +
  scale_x_continuous(breaks = seq(min(data_long$Day), max(data_long$Day), by = 4)) +
  facet_wrap(vars(factor(variable)),
    labeller = labeller(`factor(variable)` = as_labeller(
        c(MON = "bold(c)~Monocytes",
          EOS = "bold(d)~Eosinophils",
          BAS = "bold(e)~Basophils"),
        label_parsed)), nrow = 1, scales = "free_y") +
  labs(y = expression(10^3 ~ "/ " * mu * "L"), x = "Day Post-inoculation") +
  theme_minimal() +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        axis.line = element_line(color = "black"), 
        legend.text = element_text(size = 13),
        strip.text.x = element_text(size = 16),
        axis.title = element_text(size = 13),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13)) +
  guides(color = guide_legend(ncol = 4, byrow = TRUE)) -> plot_hema2_raw_mean

plot_hema <- (plot_hema1_raw_mean / plot_hema2_raw_mean) + 
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")

# ragg::agg_tiff(filename = "plot_hematology_august_10.tiff",
#                width = 15, height = 10, units = 'cm', res = 600,
#                scaling = 0.7, compression = "lzw")
# plot(plot_hema)
# invisible(dev.off())

########################################################################################

### Figure 6

## Serum Chemistry - AMY, ALT, TBIL, BUN, GLU, ALB, GLOB
## Serum - AMY, ALT
data_long %>% 
  filter(!str_detect(variable, "_p")) %>%
  filter(variable %in% c('AMY', 'ALT')) %>%
  mutate(variable = factor(variable),
         variable = droplevels(variable),
         variable = factor(variable, levels = c("ALT", "AMY")),
         Virus = factor(Virus, levels = c('H1N1', 'H3N2', 'H5_MI90', 
                                          'H5_TX37', 'H1N1_TX37', 'H3N2_TX37'))) %>%
  filter(Day > 0) %>%
  ## filter out data from euth ferrets not on collection day
  filter(!(Virus == 'H1N1_TX37' & ID == 'T7724' & Day == 11),
         !(Virus == 'H3N2_TX37' & ID == 'T7721' & Day == 7),
         !(Virus == 'H3N2_TX37' & ID == 'T7720' & Day == 8)) %>% 
  ggplot(aes(x = Day, y = value, color = Virus, group = ID)) +
  geom_ribbon(data = ribbon_df %>% 
                filter(variable %in% c('AMY', 'ALT')), 
              aes(x = Day, ymin = RI_low, ymax = RI_high),
              inherit.aes = FALSE, fill = "gray80", alpha = 0.4) +
  ## mean line
  stat_summary(aes(group = Virus), fun = mean,
               geom = "line", linewidth = 1.1) +
  scale_color_manual(values = virus_colors, labels = virus_labs) +
  scale_fill_manual(values = virus_colors, labels = virus_labs) +
  scale_x_continuous(breaks = seq(min(data_long$Day), max(data_long$Day), by = 4)) +
  facet_wrap(vars(factor(variable)),
             labeller = labeller(`factor(variable)` = as_labeller(
               c(ALT = 'bold(a)~"Alanine Aminotransferase"', 
                 AMY = "bold(b)~Amylase"),
               label_parsed)), nrow = 1, scales = "free_y") +
  labs(y = "U / L", x = "Day Post-inoculation") +
  theme_minimal() +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        axis.line = element_line(color = "black"),
        legend.text = element_text(size = 13),
        strip.text.x = element_text(size = 16),
        axis.title = element_text(size = 13),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13)) +
  guides(color = guide_legend(ncol = 4, byrow = TRUE)) -> plot_serum1


## Serum - TBIL, BUN, GLU
data_long %>% 
  filter(!str_detect(variable, "_p")) %>%
  filter(variable %in% c('TBIL', 'BUN', 'GLU')) %>%
  mutate(variable = factor(variable),
         variable = droplevels(variable),
         variable = factor(variable, levels = c('TBIL', 'BUN', 'GLU')),
         Virus = factor(Virus, levels = c('H1N1', 'H3N2', 'H5_MI90', 
                                          'H5_TX37', 'H1N1_TX37', 'H3N2_TX37'))) %>%
  filter(Day > 0) %>%
  ## filter out data from euth ferrets not on collection day
  filter(!(Virus == 'H1N1_TX37' & ID == 'T7724' & Day == 11),
         !(Virus == 'H3N2_TX37' & ID == 'T7721' & Day == 7),
         !(Virus == 'H3N2_TX37' & ID == 'T7720' & Day == 8)) %>% 
  ggplot(aes(x = Day, y = value, color = Virus, group = ID)) +
  geom_ribbon(data = ribbon_df %>% 
                filter(variable %in% c('TBIL', 'BUN', 'GLU')), 
              aes(x = Day, ymin = RI_low, ymax = RI_high),
              inherit.aes = FALSE, fill = "gray80", alpha = 0.4) +
  ## mean line
  stat_summary(aes(group = Virus), fun = mean,
               geom = "line", linewidth = 1.1) +
  scale_color_manual(values = virus_colors, labels = virus_labs) +
  scale_fill_manual(values = virus_colors, labels = virus_labs) +
  scale_x_continuous(breaks = seq(min(data_long$Day), max(data_long$Day), by = 4)) +
  facet_wrap(vars(factor(variable)),
             labeller = labeller(`factor(variable)` = as_labeller(
               c(TBIL = 'bold(c)~"Total Bilirubin"',
                 BUN = 'bold(d)~"Blood Urea Nitrogen"',
                 GLU = "bold(e)~Glucose"),
               label_parsed)), nrow = 1, scales = "free_y") +
  labs(y = "mg / dL", x = "Day Post-inoculation") +
  theme_minimal() +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        axis.line = element_line(color = "black"),
        legend.text = element_text(size = 13),
        strip.text.x = element_text(size = 16),
        axis.title = element_text(size = 13),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13)) +
  guides(color = guide_legend(ncol = 4, byrow = TRUE)) -> plot_serum2


## Serum - ALB, GLOB
data_long %>% 
  filter(!str_detect(variable, "_p")) %>%
  filter(variable %in% c('ALB', 'GLOB')) %>%
  mutate(variable = factor(variable),
         variable = droplevels(variable),
         variable = factor(variable, levels = c('ALB', 'GLOB')),
         Virus = factor(Virus, levels = c('H1N1', 'H3N2', 'H5_MI90', 
                                          'H5_TX37', 'H1N1_TX37', 'H3N2_TX37'))) %>%
  filter(Day > 0) %>%
  ## filter out data from euth ferrets not on collection day
  filter(!(Virus == 'H1N1_TX37' & ID == 'T7724' & Day == 11),
         !(Virus == 'H3N2_TX37' & ID == 'T7721' & Day == 7),
         !(Virus == 'H3N2_TX37' & ID == 'T7720' & Day == 8)) %>% 
  ggplot(aes(x = Day, y = value, color = Virus, group = ID)) +
  geom_ribbon(data = ribbon_df %>% 
                filter(variable %in% c('ALB', 'GLOB')), 
              aes(x = Day, ymin = RI_low, ymax = RI_high),
              inherit.aes = FALSE, fill = "gray80", alpha = 0.4) +
  ## mean line
  stat_summary(aes(group = Virus), fun = mean,
               geom = "line", linewidth = 1.1) +
  scale_color_manual(values = virus_colors, labels = virus_labs) +
  scale_fill_manual(values = virus_colors, labels = virus_labs) +
  scale_x_continuous(breaks = seq(min(data_long$Day), max(data_long$Day), by = 4)) +
  facet_wrap(vars(factor(variable)),
             labeller = labeller(`factor(variable)` = as_labeller(
               c(ALB = "bold(f)~Albumin",
                 GLOB = "bold(g)~Globulin"),
               label_parsed)), nrow = 1, scales = "free_y") +
  labs(y = "g / dL", x = "Day Post-inoculation") +
  theme_minimal() +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        axis.line = element_line(color = "black"),
        legend.text = element_text(size = 13),
        strip.text.x = element_text(size = 16),
        axis.title = element_text(size = 13),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13)) +
  guides(color = guide_legend(ncol = 4, byrow = TRUE)) -> plot_serum3

###

plot_serum <- (plot_serum1 / plot_serum2 / plot_serum3) + 
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")

# ragg::agg_tiff(filename = "plot_serum_august_10_1.tiff",
#                width = 15, height = 14, units = 'cm', res = 600,
#                scaling = 0.7, compression = "lzw")
# plot(plot_serum)
# invisible(dev.off())

########################################################################################
########################################################################################

### Are variables different from baseline? (within‑animal inference)

## using z-scores to detect outside (above/below) reference interval baselines

baseline_tbl <- read.csv(file = 'R_inputs/baseline_tbl.csv', header = TRUE)

dfb <- data %>% 
  select(-c(Group1:Group2, Date, Weekday, notes, Notes, 
            Blood_Collection:Yellow_Sera, Weight, Temp,
            wt_loss_cum_p, contains('euth'), contains('change'))) %>% 
  rename('NA_' = 'NA') %>%
  mutate(Day = ifelse(Day == -4, 0, Day)) %>%
  drop_na(WBC)

subject_col <- "ID"
group_cols <- c("Virus", "Treatment", "Day")

## compute z, p, and outside flag for all numeric variables present in baseline_tbl
vars <- baseline_tbl$variable
## function
compute_metrics <- function(df, baseline_tbl, vars) {
  df_long <- df %>%
    select(all_of(c(subject_col, group_cols, vars))) %>%
    pivot_longer(cols = all_of(vars), names_to = "variable", values_to = "value")
  
  df_long2 <- df_long %>%
    left_join(baseline_tbl, by = "variable") %>%
    mutate(z = (value - mean) / sd,
           p_two_sided = 2 * (1 - pnorm(abs(z))), 
           outside_RI = ifelse(is.na(value), NA, (value < RI_2.5) | (value > RI_97.5)))
  return(df_long2) }

## run function on data
dfb_long <- compute_metrics(dfb, baseline_tbl, vars)

## quick summary: counts of outside by variable, Virus, and Day
summary_flags <- dfb_long %>%
  filter(Day %in% c(1, 2, 4, 6, 10)) %>% ## filter added 25 June 2026
  group_by(variable, Day, Virus) %>%
  summarize(n = sum(!is.na(outside_RI)),
            n_outside = sum(outside_RI, na.rm = TRUE),
            prop_outside = n_outside / n,
            outside_RI = ifelse(prop_outside > 0, TRUE, FALSE),
            mean_z = mean(z, na.rm = TRUE),
            abs_mean_z = abs(mean_z),
            median_z = median(z, na.rm = TRUE),
            abs_median_z = abs(median_z),
            ## proportion with |z| > x
            prop_gtRI = mean(abs(z) > 1.96, na.rm = TRUE), ## 95% RI
            prop_gt2 = mean(abs(z) > 2, na.rm = TRUE), ## ~4.6%  of values from a standard normal exceed 2
            prop_gt3 = mean(abs(z) > 3, na.rm = TRUE)) %>%
  ungroup()
## z score of 4.15 is ~4.15 baseline SDs above the baseline mean
## positive means above baseline, negative means below baseline
View(summary_flags)

## summarize all infection days together - per Virus/variable only
summary_flags2 <- dfb_long %>%
  filter(Day > 0) %>%
  filter(Day %in% c(1, 2, 4, 6, 10)) %>% ## filter added 25 June 2026
  group_by(variable, Virus) %>%
  summarize(n = sum(!is.na(outside_RI)),
            n_outside = sum(outside_RI, na.rm = TRUE),
            prop_outside = n_outside / n,
            outside_RI = ifelse(prop_outside > 0, TRUE, FALSE),
            mean_z = mean(z, na.rm = TRUE),
            abs_mean_z = abs(mean_z),
            median_z = median(z, na.rm = TRUE),
            abs_median_z = abs(median_z),
            ## proportion with |z| > x
            prop_gtRI = mean(abs(z) > 1.96, na.rm = TRUE), ## 95% RI
            prop_gt2 = mean(abs(z) > 2, na.rm = TRUE), ## ~4.6%  of values from a standard normal exceed 2
            prop_gt3 = mean(abs(z) > 3, na.rm = TRUE)) %>%
  ungroup()
View(summary_flags2)

#write.csv(summary_flags, file = '/Results/z_scores_virus_variable_day_25June2026.csv')
#write.csv(summary_flags2, file = '/Results/z_scores_virus_variable_25June2026.csv')

## summarize each variable only (combine all Virus & Day)
summary_flags2 %>%
  group_by(variable) %>%
  summarize(n = sum(n, na.rm = TRUE),
            n_outside = sum(n_outside, na.rm = TRUE),
            prop_outside = mean(prop_outside),
            mean_z = mean(mean_z, na.rm = TRUE),
            abs_mean_z = mean(abs_mean_z),
            median_z = median(median_z, na.rm = TRUE),
            abs_median_z = mean(abs_median_z)) %>% View()

##########################################################################################
##########################################################################################
### End of Code
##########################################################################################
##########################################################################################
